=== mglass2/wrangoler/app/test/mysql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="mysqldump">
        <xs:sequence>
            <xs:element name="database" type="database" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="database">
        <xs:sequence>
            <xs:element name="table_structure" type="table_structure" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="table_structure">
        <xs:sequence>
            <xs:element name="field" type="field" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="key" type="key" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="options" type="options"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="field">
        <xs:attribute name="field" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="null" type="xs:string"/>
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="default" type="xs:string"/>
        <xs:attribute name="extra" type="xs:string"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="key">
        <xs:attribute name="table" type="xs:string"/>
        <xs:attribute name="non_unique" type="xs:int"/>
        <xs:attribute name="key_name" type="xs:string"/>
        <xs:attribute name="seq_in_index" type="xs:int"/>
        <xs:attribute name="column_name" type="xs:string"/>
        <xs:attribute name="collation" type="xs:string"/>
        <xs:attribute name="null" type="xs:string"/>
        <xs:attribute name="index_type" type="xs:string"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:complexType>


    <xs:complexType name="options">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="engine" type="xs:string"/>
        <xs:attribute name="version" type="xs:string"/>
        <xs:attribute name="row_format" type="xs:string"/>
        <xs:attribute name="rows" type="xs:string"/>
        <xs:attribute name="avg_row_length" type="xs:int"/>
        <xs:attribute name="data_length" type="xs:long"/>
        <xs:attribute name="max_data_length" type="xs:long"/>
        <xs:attribute name="index_length" type="xs:long"/>
        <xs:attribute name="data_free" type="xs:int"/>
        <xs:attribute name="create_time" type="xs:date"/>
        <xs:attribute name="update_time" type="xs:date"/>
        <xs:attribute name="check_time" type="xs:date"/>
        <xs:attribute name="collation" type="xs:string"/>
        <xs:attribute name="checksum" type="xs:string"/>
        <xs:attribute name="create_options" type="xs:string"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:complexType>

    <xs:element name="mysqldump" type="mysqldump"/>

</xs:schema>

=== mglass2/wrangoler/app/test/db_project.xml
<?xml version="1.0"?>

<mysqldump xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mysql.xsd">
    <database name="test">

        <table_structure name="userTitleMap">
            <field field="companyId" type="int(10) unsigned" null="NO" key="PRI" default="NULL" extra="" />
            <field field="securityGroupId" type="int(10) unsigned" null="NO" key="" default="NULL" extra="" />
            <field field="title" type="varchar(128)" null="NO" key="PRI" default="NULL" extra="" />
            
            <options name="userTitleMap" engine="InnoDB" collation="utf8_general_ci" comment="" />
        </table_structure>

        <table_structure name="vendor">
            <field field="vendorId" type="int(10) unsigned" null="NO" key="PRI" default="NULL" extra="auto_increment" />
            <field field="dateCreated" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="dateModified" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="userCreated" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="userModified" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="vendorName" type="varchar(64)" null="NO" key="" default="" extra="" />

            <options name="vendor" engine="InnoDB" collation="utf8_general_ci" comment="" />
        </table_structure>

        <table_structure name="vendorEmployee">
            <field field="vendorEmployeeId" type="int(10) unsigned" null="NO" key="PRI" default="NULL" extra="auto_increment" />
            <field field="dateCreated" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="dateModified" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="userCreated" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="userModified" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="firstName" type="varchar(32)" null="NO" key="" default="" extra="" />
            <field field="middleName" type="varchar(32)" null="NO" key="" default="" extra="" />
            <field field="lastName" type="varchar(32)" null="NO" key="" default="" extra="" />
            <field field="emailAddress" type="varchar(128)" null="NO" key="UNI" default="" extra="" />

            <options name="vendorEmployee" engine="InnoDB" collation="utf8_general_ci" comment="" />
        </table_structure>

        <table_structure name="vendorEmployeeRoleMap">
            <field field="vendorEmployeeRoleMapId" type="int(10) unsigned" null="NO" key="PRI" default="NULL" extra="auto_increment" />
            <field field="dateCreated" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="dateModified" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="on update CURRENT_TIMESTAMP" />
            <field field="userCreated" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="userModified" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="vendorRoleId" type="int(10) unsigned" null="NO" key="MUL" default="NULL" extra="" />
            <field field="vendorEmployeeId" type="int(10) unsigned" null="NO" key="" default="NULL" extra="" />
            <field field="financialYearId" type="int(10) unsigned" null="NO" key="" default="NULL" extra="" />
            <field field="companyId" type="int(10) unsigned" null="NO" key="" default="NULL" extra="" />
            <field field="departmentId" type="int(10) unsigned" null="NO" key="" default="NULL" extra="" />

            <options name="vendorEmployeeRoleMap" engine="InnoDB" collation="utf8_general_ci" comment="" />
        </table_structure>

        <table_structure name="vendorRole">
            <field field="vendorRoleId" type="int(10) unsigned" null="NO" key="PRI" default="NULL" extra="auto_increment" />
            <field field="dateCreated" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="dateModified" type="datetime" null="NO" key="" default="CURRENT_TIMESTAMP" extra="" />
            <field field="userCreated" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="userModified" type="int(10) unsigned" null="NO" key="" default="0" extra="" />
            <field field="vendorId" type="int(10) unsigned" null="NO" key="" default="NULL" extra="" />
            <field field="vendorRoleName" type="varchar(100)" null="NO" key="" default="NULL" extra="" />
            <field field="description" type="varchar(1000)" null="NO" key="" default="" extra="" />
            <field field="sortOrder" type="int(10) unsigned" null="NO" key="" default="0" extra="" />

            <options name="vendorRole" engine="InnoDB" collation="utf8_general_ci" comment="" />
        </table_structure>

    </database>
</mysqldump>
